# Generated by Django 5.1 on 2024-08-29 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_creation', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contests', models.ManyToManyField(related_name='Users_Contests', to='contests.contests')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Users_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_date', models.DateField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserAwards_Users', to='awards.awards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserAwards_Users', to='users.users')),
            ],
            options={
                'db_table': 'user_awards',
                'managed': True,
            },
        ),
    ]
