# Generated by Django 5.1 on 2024-09-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_awards_description_awards_code_awards_perday'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userawards',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserAwards_Awards', to='awards.awards'),
        ),
    ]
