# Generated by Django 5.1 on 2024-09-05 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0002_contests_code'),
        ('users', '0002_alter_userawards_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Extractions_Contests', to='contests.contests')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Extractions_Users', to='users.users')),
            ],
            options={
                'db_table': 'extractions',
                'managed': True,
            },
        ),
    ]
