# Generated by Django 5.1 on 2024-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractions',
            name='hour',
        ),
        migrations.AlterField(
            model_name='extractions',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
