# Generated by Django 5.1 on 2024-09-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_awards_description_awards_code_awards_perday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='code',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='perday',
        ),
    ]
