# Generated by Django 5.1 on 2024-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_remove_awards_code_remove_awards_perday'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
