# Generated by Django 5.1 on 2024-08-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contests_Awards', to='awards.awards')),
            ],
            options={
                'db_table': 'contests',
                'managed': True,
            },
        ),
    ]
