# Generated by Django 5.1 on 2024-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='code',
            field=models.CharField(default='000', max_length=10),
            preserve_default=False,
        ),
    ]
